# Generated by Django 3.0.2 on 2020-12-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=36, unique=True)),
                ('created_at', models.DateTimeField()),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('term', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'applications'
            },
        ),
    ]
