# Generated by Django 3.0.2 on 2020-12-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201230_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateuser',
            name='is_enabled',
            field=models.IntegerField(default=True),
        ),
    ]
